name: Semgrep

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  semgrep:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Run Semgrep
        run: >-
          docker run --rm
          -v "$PWD:/src" -w /src
          semgrep/semgrep:latest
          semgrep scan --config p/default --error --strict --metrics=off .
